In [1]:
import pandas
import numpy
import matplotlib.pyplot as plt
import seaborn 
import sklearn
import statsmodels.api as sm
seaborn.set()




In [2]:
data = pandas.DataFrame(data = [[1, 1], [1, 0], [0, 0], [1, 1]], columns=['Admited', 'Gender'])
data

Admited  Gender
0        1       1
1        1       0
2        0       0
3        1       1

In [3]:
y = data['Admited']
x1 = data['Gender']


In [4]:
x = sm.add_constant(x1)
x

const  Gender
0    1.0       1
1    1.0       0
2    1.0       0
3    1.0       1

In [5]:
reg_log = sm.Logit(y,x).fit()


         Current function value: 0.346574
         Iterations: 35


/home/anamaka/.local/lib/python3.8/site-packages/statsmodels/base/model.py:567: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warn("Maximum Likelihood optimization failed to converge. "


In [6]:
reg_log.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                Admited   No. Observations:                    4
Model:                          Logit   Df Residuals:                        2
Method:                           MLE   Df Model:                            1
Date:                Sun, 07 Jun 2020   Pseudo R-squ.:                  0.3837
Time:                        17:50:46   Log-Likelihood:                -1.3863
converged:                      False   LL-Null:                       -2.2493
Covariance Type:            nonrobust   LLR p-value:                    0.1889
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const       6.288e-14      1.414   4.45e-14      1.000      -2.772       2.772
Gender        31.7877   5.63e+06   5.64e-06      1.000    -1.1e+07     1.1e+07
==============================================================================

Possibly complete quasi-separation: A fraction 0.50 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [7]:
reg_log.predict(x)

0    1.0
1    0.5
2    0.5
3    1.0
dtype: float64

In [8]:
numpy.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})

In [9]:
reg_log.predict()


array([1.00, 0.50, 0.50, 1.00])

In [10]:
numpy.array(data['Admited'])


array([1, 1, 0, 1])

In [11]:
reg_log.pred_table()


array([[0.00, 1.00],
       [0.00, 3.00]])

In [12]:
cm_df = pandas.DataFrame(reg_log.pred_table())
cm_df.columns = ['Predicted 0', 'Predicted 1']
cm_df = cm_df.rename(index = {0: 'Actual 0', 1: 'Actual 1'})

In [13]:
cm_df

Predicted 0  Predicted 1
Actual 0          0.0          1.0
Actual 1          0.0          3.0

In [14]:
cm = numpy.array(cm_df)
accuracy_rate = (cm[0,0] + cm[1,1])/cm.sum()


In [15]:
accuracy_rate

0.75

In [16]:
print("Accuracy rate of the following logistic regression is " + str(accuracy_rate * 100) + "%")

Accuracy rate of the following logistic regression is 75.0%
