In [3]:
import numpy
import pandas
from sklearn.model_selection import train_test_split

In [5]:
a = numpy.arange(1,1001)
b = numpy.arange(5001, 6001)


In [6]:
train_test_split(a)
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size =0.5,random_state = 365)

In [7]:
a_train.shape, a_test.shape, b_train.shape, b_test.shape

((500,), (500,), (500,), (500,))

In [8]:
a_train

array([ 250,  299,  976,  476,  933,  491,  232,  732,  964,  610,  179,
        168,   18,  958,    6,  335,  204,  597,  925,   94,   15,  220,
        248,  664,  626,  941,  123,   13,  994,  588,  863,  824,  825,
        505,  389,  195,  364,  113,  470,  579,  477,  292,  527,  826,
        370,  625,  882,  551,  347,  263,  998,  950,  900,  548,  259,
        903,  960,  268,  315,  356,  785,  354,  239,  729,  105,  258,
        104,  945,  680,  672,   89,  116,  308,  309,  815,  939,  457,
        692,  467,  126,  525,  289,  904,  873,  214,  706,   97,  591,
        589,  831,  134,   88,  784,  405,   51,  415,  928,   29,  279,
        156,   85,  398,  115,  666,  948,  926,  984,  340,  286,  131,
        775,  736,  348,  358,   53,  766,  963,  697,  381,  612,  451,
         75,  820,  564,  890,  641,  969,  601,  603,   57,  124,    8,
        215,  304,  850,  598,  109,  122,  372,  503,  790,  643,  733,
        710,  632,  301,   11,  483,   91,  767,  2

In [9]:
a_test

array([580, 207, 822, 253, 734, 803, 617, 438, 789, 797, 865, 213, 812,
       622, 972, 699, 937, 197, 454, 151, 792, 495, 170, 394,  23, 135,
       431, 751, 270,  62, 312, 849, 562, 549,  52,  55, 226, 788,  77,
       991, 683, 566, 515,   7, 274, 303, 332, 128, 154, 210, 769, 365,
       851,  70, 254,  99, 261, 737,  63, 172, 995, 627, 748,  41, 971,
        95, 238, 534, 555, 324, 139, 761, 490, 196, 153, 252, 894, 674,
       883, 152, 430, 306, 600, 422, 233,  50, 912, 280, 121, 942, 687,
       577, 840, 891, 481, 606, 412, 380, 397, 783, 325, 409, 581,  37,
       297, 384, 391, 833, 845, 498, 417, 414,  45, 677, 834, 714,  26,
       360, 236,  98, 943, 413, 181, 935, 334, 690, 829, 722, 526, 319,
       186, 952, 218, 300, 623, 575, 434, 917, 781, 362, 242, 681, 910,
       678, 810, 497, 572, 554, 973, 407, 772, 827, 234, 420,  40, 807,
       506, 669,  60,  27,  12,  87, 901, 148, 927, 392, 418, 439, 291,
       800, 799, 796, 493, 390, 246, 855, 708, 888, 338, 185, 19

In [10]:
b_train

array([5250, 5299, 5976, 5476, 5933, 5491, 5232, 5732, 5964, 5610, 5179,
       5168, 5018, 5958, 5006, 5335, 5204, 5597, 5925, 5094, 5015, 5220,
       5248, 5664, 5626, 5941, 5123, 5013, 5994, 5588, 5863, 5824, 5825,
       5505, 5389, 5195, 5364, 5113, 5470, 5579, 5477, 5292, 5527, 5826,
       5370, 5625, 5882, 5551, 5347, 5263, 5998, 5950, 5900, 5548, 5259,
       5903, 5960, 5268, 5315, 5356, 5785, 5354, 5239, 5729, 5105, 5258,
       5104, 5945, 5680, 5672, 5089, 5116, 5308, 5309, 5815, 5939, 5457,
       5692, 5467, 5126, 5525, 5289, 5904, 5873, 5214, 5706, 5097, 5591,
       5589, 5831, 5134, 5088, 5784, 5405, 5051, 5415, 5928, 5029, 5279,
       5156, 5085, 5398, 5115, 5666, 5948, 5926, 5984, 5340, 5286, 5131,
       5775, 5736, 5348, 5358, 5053, 5766, 5963, 5697, 5381, 5612, 5451,
       5075, 5820, 5564, 5890, 5641, 5969, 5601, 5603, 5057, 5124, 5008,
       5215, 5304, 5850, 5598, 5109, 5122, 5372, 5503, 5790, 5643, 5733,
       5710, 5632, 5301, 5011, 5483, 5091, 5767, 52

In [11]:
b_test

array([5580, 5207, 5822, 5253, 5734, 5803, 5617, 5438, 5789, 5797, 5865,
       5213, 5812, 5622, 5972, 5699, 5937, 5197, 5454, 5151, 5792, 5495,
       5170, 5394, 5023, 5135, 5431, 5751, 5270, 5062, 5312, 5849, 5562,
       5549, 5052, 5055, 5226, 5788, 5077, 5991, 5683, 5566, 5515, 5007,
       5274, 5303, 5332, 5128, 5154, 5210, 5769, 5365, 5851, 5070, 5254,
       5099, 5261, 5737, 5063, 5172, 5995, 5627, 5748, 5041, 5971, 5095,
       5238, 5534, 5555, 5324, 5139, 5761, 5490, 5196, 5153, 5252, 5894,
       5674, 5883, 5152, 5430, 5306, 5600, 5422, 5233, 5050, 5912, 5280,
       5121, 5942, 5687, 5577, 5840, 5891, 5481, 5606, 5412, 5380, 5397,
       5783, 5325, 5409, 5581, 5037, 5297, 5384, 5391, 5833, 5845, 5498,
       5417, 5414, 5045, 5677, 5834, 5714, 5026, 5360, 5236, 5098, 5943,
       5413, 5181, 5935, 5334, 5690, 5829, 5722, 5526, 5319, 5186, 5952,
       5218, 5300, 5623, 5575, 5434, 5917, 5781, 5362, 5242, 5681, 5910,
       5678, 5810, 5497, 5572, 5554, 5973, 5407, 57