In [5]:
import pandas
import numpy
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn
seaborn.set()
import sklearn

In [7]:
raw_data = pandas.read_csv('8.1 1.02. Multiple linear regression.csv.csv')
raw_data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [12]:
y = raw_data['GPA']
x1 = raw_data[['SAT', 'Rand 1,2,3']]

In [16]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x1, y)

LinearRegression()

In [18]:
reg.score(x1, y)

0.40668119528142843

In [20]:
reg.intercept_


0.29603261264909486

In [21]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [26]:
reg.predict([[1700, 2], [1689, 1]])

array([3.09051403, 3.08059489])

In [37]:
r2 = reg.score(x1, y)
n = x1.shape[0]
p = x1.shape[1]
adjusted_r2 = 1 - (1-r2) * (n-1)/ (n-p-1)
adjusted_r2

0.39203134825134023

In [39]:
from sklearn.feature_selection import f_regression

f_regression(x1, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [46]:
p_values = f_regression(x1, y)[1]
p_values.round(3)

array([0.   , 0.676])

In [45]:
F_Statistic = f_regression(x1, y)[0]
F_Statistic


array([56.04804786,  0.17558437])

In [60]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x1)
x_scaled = scaler.transform(x1)
x_scaled


array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,