In [1]:
import numpy as np

In [2]:
#creates a list and saves it in my_list variable
my_list = [1,2,3,4,5]
#creates a numpy.ndarray and saves it in arr1d variable
arr1d = np.array(my_list)
#enlist the type of the variable
type(arr1d)

numpy.ndarray

In [3]:
#prints how 1d array is shown
arr1d

array([1, 2, 3, 4, 5])

In [4]:
#prints the shape or tuple of 1d array. The first parameter is the number of elements in the array
arr1d.shape

(5,)

In [5]:
#creating two dimensional array

#creates three list and saves it in their respective variables.
my_list0 = [1,2,3,4,5]
my_list1 = [5,4,3,2,1]
my_list2 = [0,1,3,5,6]

#creates a 2d array and prints how it is displayed.
arr2d = np.array([my_list0, my_list1, my_list2])
arr2d

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [0, 1, 3, 5, 6]])

In [6]:
#prints the shape of 2d array. The first parameter is number of rows and second parameter is number of columns in 2d arrays.
arr2d.shape

(3, 5)

In [7]:
#changing the shape of the ndarray
arr2d = arr2d.reshape(5,3)

In [8]:
arr2d

array([[1, 2, 3],
       [4, 5, 5],
       [4, 3, 2],
       [1, 0, 1],
       [3, 5, 6]])

In [9]:
#acessing the element from an array.
#the first parameter is for rows and second parameter is for columns.
arr2d[:,:]

array([[1, 2, 3],
       [4, 5, 5],
       [4, 3, 2],
       [1, 0, 1],
       [3, 5, 6]])

In [10]:
arr2d[3, 1]

0

In [11]:
#draw a line at the front of the first row/column and starting counting from 0 to select the rows and column easily.
arr2d[1:3, 1:3]

array([[5, 5],
       [3, 2]])